"""remove group creator/led relationship

Revision ID: 0637df76febc
Revises: a16efb913a70
Create Date: 2024-01-16 16:39:26.711244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0637df76febc'
down_revision = 'a16efb913a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_creator', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('group_creator')

    # ### end Alembic commands ###
